version: '3.4'

services:
  octaai.api:
    image: ${DOCKER_REGISTRY-}octaaiapi
    build:
      context: .
      dockerfile: Presentation/OctaAI.API/Dockerfile
    ports:
      - "5000:80"

  # octaai.angular:
  #   image: ${DOCKER_REGISTRY-}octaaiangular
  #   build:
  #     context: .
  #     dockerfile: client/octa-ai-client/Dockerfile
  #   ports:
  #     - "4300:80"
